name: Deploy to GitHub pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Build Gatsby
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - run: yarn
    
    - run: yarn deploy
      with:
          access-token: ${{ secrets.ACCESS_TOKEN }}

