name: Deploy to GitHub pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Build Gatsby
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - run: npm ci
    - run: npm run deploy